---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "docker"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: ".devcontainer"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
