pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author = dependabot[bot]
      - '#approved-reviews-by >= 1'
      - check-success = test
      - check-success = golangci-lint
    actions:
      merge:
        method: merge
  - name: automatic update for PR
    conditions:
      - author = dependabot[bot]
    actions:
      update:
