version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/github.com/k-akari/golang-rest-api-sample
    networks:
      - db
      - redis
    depends_on:
      - db
      - redis

  db:
    image: mysql/mysql-server:8.0.32
    ports:
      - 33307:3306
    environment:
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
    volumes:
      - db_data:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - db

  redis:
    image: redis:7.2.3
    container_name: redis
    ports:
      - 36379:6379
    volumes:
      - redis_data:/data
    networks:
      - redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
      PMA_PASSWORD: password
      PMA_PORT: 3306
      PMA_USER: root
    depends_on:
      - db
    networks:
      - db

volumes:
  db_data:
  redis_data:

networks:
  db:
  redis:
