services:
  api:
    container_name: dev
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3306
    volumes:
      - .:/go/src/github.com/k-akari/payment.com
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - go_mod:/go/pkg/mod
    ports:
      - 8081:8080
    stdin_open: true
    tty: true
    depends_on:
      - db
    networks:
      - db

volumes:
  go_mod:
