name: test
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
      - 'docker/*'
      - '.devcontainer/*'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.21.4
      env:
        DB_HOST: db
        DB_PORT: 3306
        REDIS_HOST: redis
        REDIS_PORT: 6379
      ports:
        - 80
    services:
      db:
        image: mysql:8.0.32
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 3306:3306
        env:
          MYSQL_PASSWORD: password
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: user
      redis:
        image: redis:7.2.3
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Setup .pem files
      run: |
        echo "$SECRET_KEY" > internal/auth/cert/secret.pem
        echo "$PUBLIC_KEY" > internal/auth/cert/public.pem
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY_CI }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY_CI }}
    - run: go test ./... -coverprofile=coverage.out
    - name: report coverage
      uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v0.54.6
